name: Deploy tag to PR Env

on:
  push:
    tags:
      - 'v*'
jobs:
  deploy-tags:
    steps:
     - name: GitHub Tag Name example 2
       run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
    runs-on: ubuntu-latest