name: Deploy tag to PR Env

on:
  push:
    branches: [main]
jobs:
  deploy-tags:
    if: endsWith(github.event.base_ref, 'main')
    steps:
     - name: GitHub Tag Name example dep
       run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
         echo "Tag name from github: ${{ toJson(github) }}"
         echo "Tag name from github: ${{ toJson(github.event.base_ref) }}"
         
    runs-on: ubuntu-latest